#!/bin/bash

if [[ ! -f ~/.vim/autoload/plug.vim ]]; then
    echo "Installing vim-plug"
    curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
        https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi

if [[ ! -d ~/.tmux/plugins/tpm ]]; then
    echo "Cloning TPM"
    git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
fi


which stow > /dev/null
if [[ $? != 0 ]]; then 
    echo "Installing stow"
    pacman --sync stow
fi

if [[ ! -f ~/.bash_custom ]]; then
    touch ~/.bash_custom
fi
if [[ ! -f ~/.zsh_custom ]]; then
    touch ~/.zsh_custom
fi
if [[ ! -f ~/.gitconfig_custom ]]; then
    touch ~/.gitconfig_custom
fi
if [[ ! -f ~/.vimrc_custom ]]; then
    touch ~/.vimrc_custom
fi
if [[ ! -f ~/.tmux_custom.conf ]]; then
    touch ~/.tmux_custom.conf
fi

stow -t ~/ .
